<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WIN-HQ5D7S9H79R" ignored="0" name="All tests" tests="27" failures="5" timestamp="16 янв 2018 15:18:01 GMT" time="1612.273" errors="0">
  <testcase name="testLogin" time="10.879" classname="graduateprojectpackage.LoginMozillaT"/>
  <testcase name="testLogin" time="8.66" classname="graduateprojectpackage.LoginMozillaT"/>
  <testcase name="testLogin" time="7.811" classname="graduateprojectpackage.LoginMozillaT"/>
  <testcase name="testLogin" time="8.041" classname="graduateprojectpackage.LoginMozillaT"/>
  <testcase name="testLogin" time="7.896" classname="graduateprojectpackage.LoginMozillaT"/>
  <testcase name="testLogin" time="7.118" classname="graduateprojectpackage.LoginMozillaT"/>
  <testcase name="testLogin" time="7.679" classname="graduateprojectpackage.LoginMozillaT"/>
  <testcase name="testLogin" time="7.296" classname="graduateprojectpackage.LoginMozillaT"/>
  <testcase name="testLogin" time="7.746" classname="graduateprojectpackage.LoginMozillaT"/>
  <testcase name="testLogin" time="10.296" classname="graduateprojectpackage.LoginOperaT"/>
  <testcase name="testLogin" time="9.12" classname="graduateprojectpackage.LoginOperaT"/>
  <testcase name="testLogin" time="7.854" classname="graduateprojectpackage.LoginOperaT"/>
  <testcase name="testLogin" time="7.494" classname="graduateprojectpackage.LoginOperaT"/>
  <testcase name="testLogin" time="8.1" classname="graduateprojectpackage.LoginOperaT"/>
  <testcase name="testLogin" time="7.479" classname="graduateprojectpackage.LoginOperaT"/>
  <testcase name="testLogin" time="7.969" classname="graduateprojectpackage.LoginOperaT"/>
  <testcase name="testLogin" time="7.348" classname="graduateprojectpackage.LoginOperaT"/>
  <testcase name="testLogin" time="7.441" classname="graduateprojectpackage.LoginOperaT"/>
  <testcase name="testMap" time="527.994" classname="graduateprojectpackage.MapMozillla"/>
  <testcase name="testOrder" time="77.708" classname="graduateprojectpackage.Order">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Salon Sébastopol] but found [-]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Salon Sébastopol] but found [-]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at graduateprojectpackage.HelpMethodsT.assertOrdersTable(HelpMethodsT.java:61)
	at graduateprojectpackage.Order.testOrder(Order.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testOrder -->
  <testcase name="testOrderOwnImage" time="89.522" classname="graduateprojectpackage.OrderOwnImage">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Salon lombard] but found [-]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Salon lombard] but found [-]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at graduateprojectpackage.HelpMethodsT.assertOrdersTable(HelpMethodsT.java:61)
	at graduateprojectpackage.OrderOwnImage.testOrderOwnImage(OrderOwnImage.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testOrderOwnImage -->
  <testcase name="testArtistInOrder" time="88.829" classname="graduateprojectpackage.OrderViaTabTests">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Salon Sébastopol] but found [-]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Salon Sébastopol] but found [-]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at graduateprojectpackage.HelpMethodsT.assertOrdersTable(HelpMethodsT.java:61)
	at graduateprojectpackage.OrderViaTabTests.testArtistInOrder(OrderViaTabTests.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testArtistInOrder -->
  <testcase name="testSalonInOrder" time="88.682" classname="graduateprojectpackage.OrderViaTabTests">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Salon opera] but found [-]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Salon opera] but found [-]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at graduateprojectpackage.HelpMethodsT.assertOrdersTable(HelpMethodsT.java:61)
	at graduateprojectpackage.OrderViaTabTests.testSalonInOrder(OrderViaTabTests.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testSalonInOrder -->
  <testcase name="testServices" time="87.823" classname="graduateprojectpackage.OrderViaTabTests">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Salon lombard] but found [-]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Salon lombard] but found [-]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at graduateprojectpackage.HelpMethodsT.assertOrdersTable(HelpMethodsT.java:61)
	at graduateprojectpackage.OrderViaTabTests.testServices(OrderViaTabTests.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testServices -->
  <testcase name="testArtistShowMore" time="82.548" classname="graduateprojectpackage.ShowMoreTests"/>
  <testcase name="testPicsShoMore" time="78.185" classname="graduateprojectpackage.ShowMoreTests"/>
  <testcase name="testSalonShowMore" time="78.983" classname="graduateprojectpackage.ShowMoreTests"/>
</testsuite> <!-- All tests -->
